# Inserts a blank line between shell prompts
add_newline = false
# Change command timeout from 500 to 1000 ms
command_timeout = 1000
# Change the default prompt format
format = """\
[╭╴](238)$env_var\
$all[╰─](238)$character"""
# Shows an icon that should be included by zshrc script based on the distribution or os
[env_var.STARSHIP_DISTRO]
format = '[$env_value](bold white)'  # removed space between distro and rest for pwsh
variable = "STARSHIP_DISTRO"
disabled = false
[memory_usage]
disabled = false
threshold = -1
symbol = " "
style = "bold yellow"
[hostname]
ssh_only = false
format =  "@ [$hostname](bold red) "
trim_at = ".companyname.com"
disabled = false
[username]
style_user = "white bold"
style_root = "red bold"
format = "[$user]($style) "
disabled = false  # disable in powershell
show_always = true
[directory]
truncation_length = 6
truncation_symbol = "…/"
home_symbol = " ~"
read_only_style = "197"
read_only = "  "
format = "in [$path]($style)[$read_only]($read_only_style) "
[git_branch]
symbol = " "
format = "on [$symbol$branch]($style) "
truncation_length = 10
truncation_symbol = "…/"
style = "bold green"
[git_status]
format = '[\($all_status$ahead_behind\)]($style) '
style = "bold green"
conflicted = "🏳"
up_to_date = " "
untracked = " "
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
stashed = " "
modified = " "
staged = '[++\($count\)](green)'
renamed = "襁 "
deleted = " "
[terraform]
format = "via [ terraform $version]($style) 壟 [$workspace]($style) "
[vagrant]
format = "via [ vagrant $version]($style) "
[docker_context]
format = "via [ $context](bold blue) "
[helm]
format = "via [ $version](bold purple) "
[python]
symbol = " "
python_binary = "python3"
[nodejs]
format = "via [ $version](bold green) "
disabled = true
[ruby]
format = "via [ $version]($style) "
#[shell]
#fish_indicator = ""
#powershell_indicator = "_"
#unknown_indicator = "mystery shell"
#style = "cyan bold"
#disabled = false
[status]
style = "bg:blue"
symbol = "🔴"
format = '[\[$symbol $common_meaning$signal_name$maybe_int\]]($style) '
map_symbol = true
disabled = false
[sudo]
style = "bold green"
symbol = "👩‍💻 "
disabled = false
[time]
disabled = true
format = '🕙[\[ $time \]]($style) '
time_format = "%T"
utc_time_offset = "-5"
time_range = "10:00:00-14:00:00"
